# Generated by Django 3.1 on 2021-11-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211101_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='update',
            new_name='updated',
        ),
    ]
